### ISSUE TITLE
'Wrap with' assist does not apply indentation

### ISSUE THREAD

**Issue by manuel-plavsic** [nank1ro/solidart#50]
When using the assists, the indentation is not applied.

E.g., when selecting "Wrap with SignalBuilder" on some Widget (e.g. `CupertinoListTile`), i.e.:

```dart
            return CupertinoListTile(
// ...
```

 instead of seeing:

```dart
            return SignalBuilder(
              signal: null,
              builder: (context, value, child) {
                return CupertinoListTile(
// ...
```

what is autocompleted is:

```dart
```dart
            return SignalBuilder(
signal: null,
builder: (context, value, child) {
return CupertinoListTile(
// ...
```

**Comment by nank1ro** [comment]
Yes I know, I think it's normal with custom lint. If you have dart format on file save, it will reindent your code.

**Comment by nank1ro** [comment]
Closing this for now, feel free to reopen if `custom_lint` has a way to take indentation into consideration.
