### ISSUE TITLE
Will autoDispose be supported in the future?

### ISSUE THREAD

**Issue by Onekki** [nank1ro/solidart#71]

**Comment by Onekki** [comment]
![screenshot20231121](https://github.com/nank1ro/solidart/assets/31927350/0d176e7f-0fe7-4707-80b2-7808a724e82f)
Signals requires manual dispose.

**Comment by nank1ro** [comment]
I need to check if this is feasible. Will update you.

**Comment by nank1ro** [comment]
implemented in the v1.3.0 of solidart, [see the docs here](https://docs.page/nank1ro/solidart/advanced/automatic-disposal)
